using System.Collections;
using System.Reflection;
using System.Text;
using MphRead;

// Build-time only. Checked-in accessors contain no runtime code generation and work on AOT.
var checkpoint = typeof(Scene).Assembly.GetType("MphRead.Mods.Replay.ReplayWorldCheckpoint")!;
var flags = BindingFlags.Static | BindingFlags.NonPublic;
var fields = (Dictionary<Type, FieldInfo[]>)checkpoint.GetField("Fields", flags)!.GetValue(null)!;
var objects = (Type[])checkpoint.GetField("ObjectTypes", flags)!.GetValue(null)!;
string contract = (string)checkpoint.GetField("Contract", flags)!.GetValue(null)!;
var output = new StringBuilder("// Generated by tools/replay-schema-generator. Do not edit by hand.\nusing System;\nusing System.IO;\nusing System.Runtime.CompilerServices;\nusing System.Runtime.InteropServices;\nnamespace MphRead.Mods.Replay;\ninternal static class ReplayCheckpointAccessors\n{\n");
var helpers = new StringBuilder();
var valueMethods = new Dictionary<Type, string>();
int accessor = 0;
bool Nameable(Type type) => !type.IsNestedPrivate && !type.IsNestedFamily && !type.IsPointer && (!type.HasElementType || Nameable(type.GetElementType()!)) && (!type.IsGenericType || type.GetGenericArguments().All(Nameable));
string Name(Type type) => type.IsArray ? Name(type.GetElementType()!) + "[" + new string(',', type.GetArrayRank() - 1) + "]"
    : type.IsGenericType ? "global::" + type.GetGenericTypeDefinition().FullName!.Split('`')[0].Replace('+', '.') + "<" + string.Join(",", type.GetGenericArguments().Select(Name)) + ">"
    : "global::" + type.FullName!.Replace('+', '.');
string Get(FieldInfo field, string instance)
{
    if (field.IsPublic && !field.Name.Contains('<')) return instance + ".@" + field.Name;
    string id = "Get" + accessor++;
    helpers.AppendLine($"    [UnsafeAccessor(UnsafeAccessorKind.Field, Name = \"{field.Name}\")] private static extern ref {Name(field.FieldType)} {id}({(field.DeclaringType!.IsValueType ? "ref " : "")}{Name(field.DeclaringType)} value);");
    return id + "(" + (field.DeclaringType.IsValueType ? "ref " : "") + instance + ")";
}
bool Bulk(Type type) => type == typeof(byte) || type == typeof(sbyte) || type == typeof(short)
    || type == typeof(ushort) || type == typeof(int) || type == typeof(uint) || type == typeof(long)
    || type == typeof(ulong) || type == typeof(float) || type == typeof(double)
    || type.FullName is "OpenTK.Mathematics.Vector2" or "OpenTK.Mathematics.Vector3" or "OpenTK.Mathematics.Vector4" or "OpenTK.Mathematics.Matrix4";
string Write(Type type, string expr)
{
    if (type == typeof(object)) return $"ReplayWorldCheckpoint.WriteValue(w, typeof(object), {expr}, reference);";
    if (type == typeof(string)) return $"w.Write({expr} != null); if ({expr} != null) w.Write({expr});";
    if (type.IsEnum) return $"w.Write(({Name(Enum.GetUnderlyingType(type))}){expr});";
    if (type == typeof(char)) return $"w.Write((ushort){expr});";
    if (type.IsPrimitive) return $"w.Write({expr});";
    if (!type.IsValueType) return $"w.Write(reference({expr}));";
    if (!valueMethods.TryGetValue(type, out string? method))
    {
        method = "Value" + valueMethods.Count; valueMethods.Add(type, method);
        var body = new StringBuilder();
        if (Nullable.GetUnderlyingType(type) is Type inner)
            body.AppendLine($"        w.Write(value.HasValue); if (value.HasValue) {{ {Write(inner, "value.Value")} }}");
        else
            foreach (var field in type.GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic).OrderBy(f => f.MetadataToken))
                body.AppendLine("        " + Write(field.FieldType, Get(field, "value")));
        if (Bulk(type)) body.Insert(0, "        if (BitConverter.IsLittleEndian) { w.Write(MemoryMarshal.AsBytes(MemoryMarshal.CreateReadOnlySpan(ref value, 1))); return; }\n");
        helpers.AppendLine($"    private static void {method}(BinaryWriter w, {Name(type)} value, Func<object?, int> reference)\n    {{\n{body}    }}");
    }
    return $"{method}(w, {expr}, reference);";
}
output.AppendLine($"    internal const string Contract = \"{contract}\";");
output.AppendLine("    internal static bool Write(BinaryWriter w, object value, Func<object?, int> reference)\n    {\n        Type type = value.GetType();");
foreach (Type type in objects)
{
    if (!Nameable(type)) { Console.WriteLine("Skipped type: " + type); continue; }
    var body = new StringBuilder();
    if (fields.TryGetValue(type, out var schema))
    {
        if (schema.Any(f => !Nameable(f.FieldType) || !Nameable(f.DeclaringType!))) { Console.WriteLine("Skipped fields: " + type + " " + string.Join(",", schema.Where(f => !Nameable(f.FieldType)).Select(f => f.Name + ":" + f.FieldType))); continue; }
        foreach (var field in schema) body.AppendLine("            " + Write(field.FieldType, Get(field, "item")));
    }
    else if (type.IsArray || type.IsGenericType)
    {
        Type element = type.IsArray ? type.GetElementType()! : type.GetGenericArguments()[0];
        if (type.IsArray)
            for (int rank = 0; rank < type.GetArrayRank(); rank++) body.AppendLine($"            w.Write(item.GetLength({rank}));");
        else body.AppendLine("            w.Write(item.Count);");
        if (Bulk(element) && (type.IsArray && type.GetArrayRank() == 1 || type.IsGenericType && type.GetGenericTypeDefinition() == typeof(List<>)))
            body.AppendLine($"            if (BitConverter.IsLittleEndian) w.Write(MemoryMarshal.AsBytes({(type.IsArray ? "item.AsSpan()" : "CollectionsMarshal.AsSpan(item)")})); else");
        body.AppendLine($"            foreach (var entry in item) {{ {Write(element, "entry")} }}");
    }
    else continue;
    output.AppendLine($"        if (type == typeof({Name(type)}))\n        {{\n            var item = ({Name(type)})value;\n{body}            return true;\n        }}");
}
output.AppendLine("        return false;\n    }");
output.Append(helpers).AppendLine("}");
var asset = typeof(Scene).Assembly.GetType("MphRead.Mods.Replay.ReplayAssetCheckpoint")!;
output.AppendLine("internal static class ReplayAssetAccessors\n{");
output.AppendLine($"    internal const string Contract = \"{asset.GetField("AccessorContract", flags)!.GetValue(null)}\";");
string AssetWrite(Type type, string expr)
{
    if (Nullable.GetUnderlyingType(type) is Type inner)
        return $"w.Write({expr}.HasValue); if ({expr}.HasValue) {{ {AssetWrite(inner, expr + ".Value")} }}";
    if (type.IsEnum) return $"w.Write((int){expr});";
    if (type.IsPrimitive) return $"w.Write({expr});";
    if (type.Name is "Vector3" or "Vector4")
        return string.Join(" ", (type.Name == "Vector3" ? new[] { "X", "Y", "Z" } : new[] { "X", "Y", "Z", "W" }).Select(c => $"w.Write({expr}.{c});"));
    if (type.Name == "Matrix4") return $"{{ var matrix = {expr}; if (BitConverter.IsLittleEndian) w.Write(MemoryMarshal.AsBytes(MemoryMarshal.CreateReadOnlySpan(ref matrix, 1))); else for (int r = 0; r < 4; r++) for (int c = 0; c < 4; c++) w.Write(matrix[r, c]); }}";
    if (type.Name == "ColorRgb") return $"w.Write({expr}.Red); w.Write({expr}.Green); w.Write({expr}.Blue);";
    throw new InvalidOperationException(type.ToString());
}
foreach (string name in new[] { "Node", "Mesh", "Material" })
{
    var properties = (PropertyInfo[])asset.GetField(name + "Fields", flags)!.GetValue(null)!;
    output.AppendLine($"    internal static void Write(BinaryWriter w, {Name(properties[0].DeclaringType!)} value)\n    {{");
    foreach (var property in properties) output.AppendLine("        " + AssetWrite(property.PropertyType, "value." + property.Name));
    output.AppendLine("    }");
}
output.AppendLine("}");
File.WriteAllText(args[0], output.ToString());
Console.WriteLine($"Generated {accessor} field accessors and {valueMethods.Count} value serializers.");
